version: '3.8'

services:

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mean-network

  backend:
    image: shashankkanade25/mean-backend:latest
    container_name: backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/dd_db
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - mean-network

  frontend:
    image: shashankkanade25/mean-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - mean-network

volumes:
  mongo-data:

networks:
  mean-network:
    driver: bridge
