name: CI/CD Pipeline - MEAN Stack

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Backend Image
      run: |
        docker build -t shashankkanade25/mean-backend:latest ./backend

    - name: Build Frontend Image
      run: |
        docker build -t shashankkanade25/mean-frontend:latest ./frontend

    - name: Push Backend Image
      run: docker push shashankkanade25/mean-backend:latest

    - name: Push Frontend Image
      run: docker push shashankkanade25/mean-frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/mean-app
          docker compose down
          docker compose pull
          docker compose up -d
